project_id = "uxzyicmsastcrldfvgpf"

[functions.backfill-prices]
verify_jwt = false

[functions.scrape-prices]
verify_jwt = false

[functions.sync-dosm]
verify_jwt = false

[functions.sanity-check-data]
verify_jwt = false
